site_name: My Docs
site_url: https://mike-docs.example
theme:
  name: material
  palette: 
    scheme: slate
    primary: green
    accent: deep purple
  features:
    - navigation.footer
    # - navigation.tabs


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
    social:
      - icon: fontawesome/brands/mastodon 
        link: https://fosstodon.org/@squidfunk

copyright: Copyright &copy 2025 Michael Armijo