site_name: My Docs
site_url: https://mike-docs.example
theme:
  name: material
  palette: 
    scheme: slate
    primary: green
    accent: deep purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences